inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/SymbolArray:
  EnforcedStyle: brackets
